export const CATEGORIAS = [
  "Todas", "Supermercados", "Ropa", "Zapatos y Joyería", "Cine", "Viajes", "Belleza y Otros", "Tecnología", "Gaming",
];

export const OFERTAS_LOCALES = [
  { id: "mx-1", tienda: "Walmart", titulo: "Liquidación de temporada en hogar y despensa", descuento: 40, vigenciaInicio: "2026-09-15", vigenciaFin: "2026-10-31", msi: 12, banco: "Banamex, HSBC", cupon: "WALMART40", codigo: "WM-LIQ", categoria: "Supermercados", descripcion: "Hasta 40% en hogar y despensa.", fuente: "catalogo-local", url: "https://www.walmart.com.mx" },
  { id: "mx-2", tienda: "Chedraui", titulo: "Electrónicos con MSI", descuento: 15, vigenciaInicio: "2026-10-01", vigenciaFin: "2026-10-31", msi: 18, banco: "BBVA, Banorte, Santander", cupon: "CHEDRAUI18", codigo: "CH-MSI", categoria: "Supermercados", descripcion: "15% + 18 meses sin intereses.", fuente: "catalogo-local", url: "https://www.chedraui.com.mx" },
  { id: "mx-3", tienda: "Soriana", titulo: "2x1 en limpieza del hogar", descuento: 50, vigenciaInicio: "2026-09-20", vigenciaFin: "2026-10-25", msi: 0, banco: "N/A", cupon: "SORIANA2X1", codigo: "SO-2X1", categoria: "Supermercados", descripcion: "Lleva 2 y paga 1 en limpieza.", fuente: "catalogo-local", url: "https://www.soriana.com" },
  { id: "mx-4", tienda: "HEB", titulo: "Despensa y carnes seleccionadas", descuento: 30, vigenciaInicio: "2026-10-01", vigenciaFin: "2026-10-31", msi: 3, banco: "Banorte, BBVA", cupon: "HEB30", codigo: "HEB-DESP", categoria: "Supermercados", descripcion: "Hasta 30% en despensa y carnes.", fuente: "catalogo-local", url: "https://www.heb.com.mx" },
  { id: "mx-5", tienda: "Costco", titulo: "Electrónicos para socios", descuento: 15, vigenciaInicio: "2026-10-01", vigenciaFin: "2026-10-31", msi: 12, banco: "Amex, Banamex", cupon: "COSTCO15", codigo: "CO-ELEC", categoria: "Supermercados", descripcion: "15% + 12 MSI. Requiere membresía.", fuente: "catalogo-local", url: "https://www.costco.com.mx" },
  { id: "mx-6", tienda: "La Comer", titulo: "Abarrotes y limpieza", descuento: 35, vigenciaInicio: "2026-09-22", vigenciaFin: "2026-10-28", msi: 3, banco: "Banorte, Santander", cupon: "LACOMER35", codigo: "LC-OCT26", categoria: "Supermercados", descripcion: "Descuentos en limpieza y despensa.", fuente: "catalogo-local", url: "https://www.lacomer.com.mx" },
  { id: "mx-7", tienda: "Bodega Aurrera", titulo: "Precios bajos en básicos", descuento: 20, vigenciaInicio: "2026-09-15", vigenciaFin: "2026-10-31", msi: 0, banco: "N/A", cupon: "AURRERA20", codigo: "BA-ABAR", categoria: "Supermercados", descripcion: "20% en abarrotes seleccionados.", fuente: "catalogo-local", url: "https://www.bodegaaurrera.com.mx" },
  { id: "mx-8", tienda: "Fresko", titulo: "Frutas y verduras (vencida de ejemplo)", descuento: 20, vigenciaInicio: "2026-09-01", vigenciaFin: "2026-09-20", msi: 0, banco: "Todas las tarjetas", cupon: "FRESKO20", codigo: "FR-VERD", categoria: "Supermercados", descripcion: "Ejemplo vencido: el filtro la oculta.", fuente: "catalogo-local", url: "https://www.lacomer.com.mx" },
  { id: "mx-9", tienda: "Zara", titulo: "Liquidación mid-season", descuento: 50, vigenciaInicio: "2026-09-10", vigenciaFin: "2026-10-31", msi: 6, banco: "Todas las tarjetas participantes", cupon: "ZARA50", codigo: "ZA-MID", categoria: "Ropa", descripcion: "Hasta 50% en seleccionados.", fuente: "catalogo-local", url: "https://www.zara.com/mx" },
  { id: "mx-10", tienda: "H&M", titulo: "Temporada anterior", descuento: 50, vigenciaInicio: "2026-09-20", vigenciaFin: "2026-10-31", msi: 6, banco: "Banorte, HSBC", cupon: "HM50", codigo: "HM-LIQ", categoria: "Ropa", descripcion: "Liquidación de temporada anterior.", fuente: "catalogo-local", url: "https://www2.hm.com/es_mx" },
  { id: "mx-11", tienda: "Nike", titulo: "Calzado y ropa deportiva", descuento: 30, vigenciaInicio: "2026-09-01", vigenciaFin: "2026-10-31", msi: 6, banco: "BBVA, Amex", cupon: "NIKE30", codigo: "NI-SPORT", categoria: "Ropa", descripcion: "Hasta 30% en seleccionado.", fuente: "catalogo-local", url: "https://www.nike.com/mx" },
  { id: "mx-12", tienda: "Adidas", titulo: "Liquidación de temporada", descuento: 40, vigenciaInicio: "2026-09-01", vigenciaFin: "2026-10-31", msi: 3, banco: "Banorte, Santander", cupon: "ADIDAS40", codigo: "AD-LIQ", categoria: "Ropa", descripcion: "Hasta 40% temporada anterior.", fuente: "catalogo-local", url: "https://www.adidas.mx" },
  { id: "mx-13", tienda: "Tous", titulo: "Joyería y accesorios", descuento: 20, vigenciaInicio: "2026-09-20", vigenciaFin: "2026-10-31", msi: 12, banco: "Banamex, Santander", cupon: "TOUS20", codigo: "TO-JOY", categoria: "Zapatos y Joyería", descripcion: "20% + 12 meses sin intereses.", fuente: "catalogo-local", url: "https://www.tous.com/mx" },
  { id: "mx-14", tienda: "Miniso", titulo: "Accesorios y hogar", descuento: 40, vigenciaInicio: "2026-09-01", vigenciaFin: "2026-10-31", msi: 0, banco: "N/A", cupon: "MINISO40", codigo: "MI-LIQ", categoria: "Zapatos y Joyería", descripcion: "Hasta 40% en temporada.", fuente: "catalogo-local", url: "https://www.miniso.com.mx" },
  { id: "mx-15", tienda: "Cinépolis", titulo: "Combo 2x1 en boletos", descuento: 50, vigenciaInicio: "2026-09-22", vigenciaFin: "2026-11-15", msi: 0, banco: "N/A", cupon: "CINEPOLIS2X1", codigo: "CP-2X1", categoria: "Cine", descripcion: "2x1 lunes a jueves en salas tradicionales.", fuente: "catalogo-local", url: "https://www.cinepolis.com" },
  { id: "mx-16", tienda: "Cinemark", titulo: "Martes de descuento", descuento: 40, vigenciaInicio: "2026-10-01", vigenciaFin: "2026-11-15", msi: 0, banco: "N/A", cupon: "CINEMARK40", codigo: "CM-MARTES", categoria: "Cine", descripcion: "40% en boletos los martes.", fuente: "catalogo-local", url: "https://www.cinemark.com.mx" },
  { id: "mx-17", tienda: "Despegar.com", titulo: "Vuelos nacionales", descuento: 30, vigenciaInicio: "2026-09-15", vigenciaFin: "2026-10-31", msi: 12, banco: "Banorte, BBVA, Amex", cupon: "DESPEGAR30", codigo: "DE-VUELOS", categoria: "Viajes", descripcion: "Hasta 30% + 12 MSI.", fuente: "catalogo-local", url: "https://www.despegar.com.mx" },
  { id: "mx-18", tienda: "Booking.com", titulo: "Hoteles en México", descuento: 25, vigenciaInicio: "2026-10-01", vigenciaFin: "2026-10-31", msi: 6, banco: "Visa, Mastercard", cupon: "BOOKING25", codigo: "BO-HOTEL", categoria: "Viajes", descripcion: "25% en hoteles seleccionados.", fuente: "catalogo-local", url: "https://www.booking.com" },
  { id: "mx-19", tienda: "Sephora", titulo: "Maquillaje y skincare", descuento: 20, vigenciaInicio: "2026-09-20", vigenciaFin: "2026-10-31", msi: 6, banco: "BBVA, Amex", cupon: "SEPHORA20", codigo: "SE-BEAUTY", categoria: "Belleza y Otros", descripcion: "20% + 6 MSI.", fuente: "catalogo-local", url: "https://www.sephora.com.mx" },
  { id: "mx-20", tienda: "Apple", titulo: "iPhone a meses sin intereses", descuento: 0, vigenciaInicio: "2026-10-01", vigenciaFin: "2026-11-15", msi: 24, banco: "Banorte, BBVA, Santander, HSBC", cupon: "APPLE24MSI", codigo: "AP-IPHONE", categoria: "Tecnología", descripcion: "24 meses sin intereses con tarjetas participantes.", fuente: "catalogo-local", url: "https://www.apple.com/mx" },
  { id: "mx-21", tienda: "Liverpool", titulo: "Venta especial moda y tecnología", descuento: 40, vigenciaInicio: "2026-09-20", vigenciaFin: "2026-10-31", msi: 12, banco: "Liverpool, Banorte", cupon: "LIVERPOOL40", codigo: "LI-ESP", categoria: "Belleza y Otros", descripcion: "Hasta 40% + 12 MSI.", fuente: "catalogo-local", url: "https://www.liverpool.com.mx" },
  { id: "mx-22", tienda: "Coppel", titulo: "Electrodomésticos", descuento: 25, vigenciaInicio: "2026-09-01", vigenciaFin: "2026-10-31", msi: 24, banco: "Coppel, Banorte", cupon: "COPPEL25", codigo: "CO-ELEC", categoria: "Tecnología", descripcion: "25% + hasta 24 meses sin intereses.", fuente: "catalogo-local", url: "https://www.coppel.com" },
  { id: "mx-23", tienda: "Best Buy", titulo: "Electrónicos seleccionados", descuento: 20, vigenciaInicio: "2026-09-20", vigenciaFin: "2026-10-31", msi: 18, banco: "Banorte, Amex, BBVA", cupon: "BESTBUY20", codigo: "BB-ELEC", categoria: "Tecnología", descripcion: "Hasta 20% + 18 MSI.", fuente: "catalogo-local", url: "https://www.bestbuy.com.mx" },
  { id: "mx-24", tienda: "Elektra", titulo: "Tecnología a MSI", descuento: 10, vigenciaInicio: "2026-10-01", vigenciaFin: "2026-11-15", msi: 24, banco: "Elektra, Banorte", cupon: "ELEKTRA24", codigo: "EL-TEC", categoria: "Tecnología", descripcion: "10% + hasta 24 MSI.", fuente: "catalogo-local", url: "https://www.elektra.com.mx" }
];
